### ISSUE TITLE
Add chain pattern to AddFieldValidation (and future AddFieldValidations)

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/lcFormValidation#27]
By doing this we could get this sugar sintax:

```javascript
    this._validationEngine
           .addFieldValidation('fullname', requiredValidationHandler)
           .addFieldValidation('email', requiredValidationHandler)
           .addFieldValidation('email', emailValidationHandler);
```

This should be implemented in both: _addfieldValidation_ and _addFieldValidationAsync_

You can find ValidationEngine file in this path:

./lib/src/validationEngine.ts

We should add a test where we check that in fact we are getting chain pattern, path test:

./lib/src/spec/validationEngine.spec.ts

**Comment by crsanti** [comment]
What about multiple validators in an array??

``` javascript
this._validationEngine
  .addFieldValidation('fullname', requiredValidationHandler)
  .addFieldValidation('email', [emailValidationHandler, requiredValidationHandler])
```

**Comment by brauliodiez** [comment]
I have created a separate issue for this: #28

**Comment by crsanti** [comment]
Ok, didn't see that :+1:

**Comment by brauliodiez** [comment]
Merged, and added to the changelog.md, we will compile some updates then release a new version.
