### ISSUE TITLE
Add coding style guide

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/lcFormValidation#31]
Start with something very simple:

- Standard js casing.
- Use spaces instead of tabs, use 2 spaces = 1 tab.

Then talk with team about which rules to add and go progressively adding them.

**Comment by crsanti** [comment]
I've done a tslint.json with (almost) all possible rules [here](https://gist.github.com/crsanti/6492bcaca50b4e3eec2be4328b2f2d5e). We could take that as starting point and adapt it to enhance the code consistency.
