### ISSUE TITLE
[core-js] Duplicate identified 'export='

### ISSUE THREAD

**Issue by crsanti** [Lemoncode/lcFormValidation#36]
There are tons of errors when starting sample 00 SimpleForm related to TypeScript and compilation with webpack:

```
ERROR in <<PATH>>/samples/react/00 SimpleForm/node_modules/@types/core-js/index.d.ts
(3069,5): error TS2300: Duplicate identifier 'export='.
```

Steps to reproduce:
- Clone the repository
- cd samples/react/00\ SimpleForm/
- npm install
- npm start

**Comment by nasdan** [comment]
Can we close this issue?

**Comment by brauliodiez** [comment]
We will move to TS + Babel, we won't make use of core-js
