### ISSUE TITLE
Set to private property FieldValidationResult.key

### ISSUE THREAD

**Issue by nasdan** [Lemoncode/lcFormValidation#41]
Right now, we have:

```javascript
export class FieldValidationResult {
  key: string;
  type: string;
  succeeded: boolean;
  errorMessage: string;

  constructor() {
    this.key = '';
    this.type = '';
    this.succeeded = false;
    this.errorMessage = '';
  }
}
```

When a user has to create validation function that resolve a FieldValidationResult, he has to provide an empty key property:

e.g:
### ./requiredValidation.ts
```javascript
export const required => (vm, value) : FieldValidationResult => {
  return {
    key: '',
    type : 'REQUIRED',
    succeeded : (value && value.length > 0),
    errorMessage : 'Mandatory field',
  }
}
```

I think `key` property should be a private property because it's only used internally

**Comment by crsanti** [comment]
I'll work on this.

**Comment by crsanti** [comment]
The `key` property is actually assigned by `_validationEngine`, to solve that usage case we only have to set `key` as optional.
