### ISSUE TITLE
Feedback improvements readme.md

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/lcFormValidation#77]
From a reviewer:

I think that it would be could to have some codepens
but hen examples in readme I like a lot more
Solutions to common problems

How do I make sure validations run step by step:
stepByStepValidation.js

How do I make sure validations

**Comment by RosanaRufer** [comment]
Hi, 
1. Do we have a lemoncode plunkr account to host the plunkr examples?.
2. What do you think about adding a plunkr in vanilla javascript without jQuery like this one?:

![lc-form-validation-vanilla](https://cloud.githubusercontent.com/assets/4906291/25066959/42979d8e-2235-11e7-9b41-0a43577d5778.gif)

3. Should our plunkrs meet any styling requirement? :thinking: (they could look more attractive but maybe it would overload the examples?)

4. Also, I don't think it is practical for maintenance to have duplicated documentation in readme.md and github page. Usually readme.md should be short and contain:
  * Short description, what is cool about it.
  * How to download/install
  * Link to the github page for documentation and tutorials.


So my first go on documentation improvements would be focused on:
1. Move tutorial and library usage guide to the github page.
2. Try to have a clean, catchy and easy to read readme.md (play with the 'agnostic' concept, add frameworks icons...)
3. [This is a vague idea] I would merge the current readme.md content into the github page and, of course, sort the documentation (by framework, [like in ui-router](https://ui-router.github.io/), and from simple cases to more complex scenarios) . Thinking on a potential user that wants to quickly find what he's interested in. Of, course, plunkrs always present.

... I have more ideas to ask you about and discuss but this is enough for now. What do you think?

**Comment by brauliodiez** [comment]
About the plunkr looks great, I think it would be a good idea to move it to codepen (it's the hype online editor, and offers more goodies). I have to check if it's possible to create a lemon group there.

About the updates you mention on the doc, they look quite interesting, give a try on a branch and we can go for a review.

Thanks a lo @totemika

**Comment by RosanaRufer** [comment]
Hi, this is one approximation to organizing the documentation into related content. It may feel uncomfortable to you to reorganize it but, please take a look and give me some feedback on what you think. Of course, CodePens or similar are important. @crsanti 

[lc-form-validation_documentation_organization.pdf](https://github.com/Lemoncode/lcFormValidation/files/965174/lc-form-validation_documentation_organization.pdf)

**Comment by Totemika** [comment]
Also, how do we reference the library in the CodePens? In Plunkr it's easy to add a file right there but with CodePen we need to have it available on a link.

**Comment by RosanaRufer** [comment]
And the most basic example in CodePen: https://codepen.io/Totemika/pen/zwZjmB

**Comment by brauliodiez** [comment]
New doc proposal looks great, lot of work to be done on this refactor, will you work on that, I volunteer as reviewr :)

Codepens or plunkrs are great, the advantage of codepen is that they offer you e.g. es6

**Comment by brauliodiez** [comment]
I like this approach:

http://react-toolbox.com/#/components

But wont fit on lcFormValidaton

**Comment by RosanaRufer** [comment]
Yes I want to work on the refactor but I also want you all to agree or discuss on the basic concepts so I don't get stuck in a path you are not ok with.

Regarding the react toolbox approach, what do you like about it? The way they structure the content, the template? both? What would you reject? The navigation pattern is 💯 % compatible with my suggestion 👌

 Which are your favorite and your most hated documentations and what good and bad do they have?

**Comment by RosanaRufer** [comment]
For example React toolbox fail: not responsive; you can't read a 💩 on mobile.

**Comment by brauliodiez** [comment]
The toolbox playground is more intented just to be tried on desktop, what I like is that you can even modify the samples, we don't need to get into that level, codepen's  enough, and we are making a different development.

**Comment by brauliodiez** [comment]
Adding @JaimeSalas and @Nasdan , the proposel you provide up there in a comment in PDF look quite good, feedback welcomed

**Comment by nasdan** [comment]
I like the PDF proposal because it reuses documentation. it's a pain in the neck when you have to update it in several places.
