### ISSUE TITLE
Add validateField in Get Started section 

### ISSUE THREAD

**Issue by crsanti** [Lemoncode/lcFormValidation#78]
Right now there is only `validateForm` in [Overview](//lemoncode.github.io/lcFormValidation/#overview).

Edit
> _"Finally apply validation when your data needs to be validate (e.g. a submit event handler):"_
> ...

and introduce `validateField` with an example.

**Comment by RosanaRufer** [comment]
Hi @crsanti would you be willing to discuss over documentation structure? What do you consider is the difference between 'Get started' and 'Tutorial' ? How do you think we can make the docs to be the easier for the consumer to read and find what he's looking for?

**Comment by brauliodiez** [comment]
About this is just an issue on the actual documentation, is missing a validateField sample
