### ISSUE TITLE
Documentation template and styling

### ISSUE THREAD

**Issue by RosanaRufer** [Lemoncode/lcFormValidation#80]
- [ ] favicon
- [ ] color palette according to LemonCode branding
- [ ] logotype?  (I have a sketch but I would ask a proper designer)

**Note:** For now I am going to focus only on content, I won't try to style anything but this issue is open for discussion too.

**Comment by brauliodiez** [comment]
A logo would be great if you can share the sketch we can provide some ideas as well.

Color palette, we have tried to use a similar one but probably doesn't fit.

favicon, ¿ Based on logo?
